import type { Config } from "tailwindcss";

let preset: Partial<Config> = {};
try {
  // dist/tokens/tailwind.preset.js is generated by `pnpm tokens:sync`.
  // Falls back to an empty preset on first run before tokens have been pulled.
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  preset = require("./dist/tokens/tailwind.preset.js");
} catch {
  preset = { theme: { extend: {} } };
}

const config: Config = {
  presets: [preset as Config],
  content: [
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
    "./.storybook/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
};

export default config;
