/**
 * Capture per-viewport renders of the *target* site (Svelte) for a given
 * storyId and place them under tests/parity/__captures__/. The parity spec
 * generated by /port-to-svelte then diffs these against the workshop's
 * .lostpixel/current/<storyId>--<viewport>.png.
 *
 * Args:
 *   --story <storyId>
 *   --route <relative-route>     e.g. "/parity/dice-tray" or "/character"
 *   --target-url <url>           the running target dev/preview URL, e.g. http://localhost:4173
 */
import path from "node:path";
import { writeFile } from "node:fs/promises";
import { parseArgs, requireArg } from "./_lib/args.js";
import { ensureDir } from "./_lib/fs.js";
import { REPO_ROOT, VIEWPORTS } from "./_lib/paths.js";

async function main(): Promise<void> {
  const args = parseArgs();
  const storyId = requireArg(args, "story");
  const route = requireArg(args, "route");
  const targetUrl = requireArg(args, "target-url");

  const outDir = path.join(REPO_ROOT, "tests", "parity", "__captures__");
  await ensureDir(outDir);

  let chromium: typeof import("playwright").chromium;
  try {
    ({ chromium } = await import("playwright"));
  } catch (err) {
    throw new Error(`playwright not installed. Underlying: ${(err as Error).message}`);
  }

  const url = new URL(route, targetUrl).toString();
  const browser = await chromium.launch();
  try {
    for (const w of VIEWPORTS) {
      const ctx = await browser.newContext({
        viewport: { width: w, height: w === 375 ? 812 : w === 768 ? 1024 : w === 1280 ? 800 : 1080 },
        reducedMotion: "reduce",
      });
      const page = await ctx.newPage();
      await page.addStyleTag({ content: `*,*::before,*::after{animation:none!important;transition:none!important}` });
      await page.goto(url, { waitUntil: "networkidle" });
      const png = await page.screenshot({ fullPage: true });
      await writeFile(path.join(outDir, `${storyId}--${w}.png`), png);
      await ctx.close();
    }
  } finally {
    await browser.close();
  }
  console.log(`parity-capture: wrote ${VIEWPORTS.length} captures for ${storyId} at ${url}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
