/**
 * Reads Figma variables (via REST or local snapshot in dist/tokens) and pushes
 * them to the Stitch project as a DesignSystem. Logs unmapped variables for
 * verbal compensation in prompts (see docs/stitch-playbook.md).
 *
 * Implementer note: Figma's `mcp__figma__get_variable_defs` is the canonical
 * read path when running inside Claude Code. From the CLI we fall back to the
 * REST API. Stitch's DesignSystem schema is unverified at the time of writing
 * — confirm against the SDK and adjust the `toStitchDesignSystem()` mapping.
 */
import path from "node:path";
import { readFile } from "node:fs/promises";
import { DIST_TOKENS, REPO_ROOT, STITCH_DIR } from "./_lib/paths.js";
import { ensureDir, fileExists, readJson, writeJsonAtomic } from "./_lib/fs.js";
import { getStitchClient } from "./_lib/stitch.js";

interface FigmaTokens {
  colors: Record<string, string>;
  typography: Record<string, { family: string; weight?: number; size?: number; lineHeight?: number }>;
  spacing: Record<string, number>;
  radii: Record<string, number>;
  shadows: Record<string, string>;
}

interface DesignSystemSnapshot {
  syncedAt: string;
  unmapped: string[];
  raw: FigmaTokens;
}

async function loadFigmaTokens(): Promise<FigmaTokens> {
  // Prefer the local snapshot generated by update-tokens.ts.
  const snapshotPath = path.join(DIST_TOKENS, "tokens.json");
  if (await fileExists(snapshotPath)) {
    const text = await readFile(snapshotPath, "utf8");
    return JSON.parse(text) as FigmaTokens;
  }
  throw new Error(
    `Tokens snapshot not found at ${snapshotPath}. Run \`pnpm tokens:sync\` first to pull from Figma.`,
  );
}

function toStitchDesignSystem(tokens: FigmaTokens): { ds: unknown; unmapped: string[] } {
  const unmapped: string[] = [];

  // Stitch's DesignSystem schema is implementation-specific. The shape below is a
  // reasonable starting point; the implementer must reconcile against the SDK.
  const ds = {
    palette: tokens.colors,
    typography: Object.fromEntries(
      Object.entries(tokens.typography).map(([name, t]) => [
        name,
        { family: t.family, weight: t.weight ?? 400, size: t.size ?? 14 },
      ]),
    ),
    spacing: tokens.spacing,
  };

  // Variables that don't map cleanly to the Stitch DesignSystem schema:
  for (const radiusName of Object.keys(tokens.radii)) unmapped.push(`radii.${radiusName}`);
  for (const shadowName of Object.keys(tokens.shadows)) unmapped.push(`shadows.${shadowName}`);

  return { ds, unmapped };
}

async function main(): Promise<void> {
  await ensureDir(STITCH_DIR);
  const projectsRecord =
    (await readJson<Record<string, { id: string }>>(path.join(STITCH_DIR, "projects.json"))) ?? {};
  const purpose = process.env.STITCH_PROJECT_PURPOSE ?? "rpg-site";
  const projectId = process.env.STITCH_PROJECT_ID ?? projectsRecord[purpose]?.id;
  if (!projectId) {
    throw new Error("No Stitch project initialized. Run `pnpm stitch:init` first.");
  }

  const tokens = await loadFigmaTokens();
  const { ds, unmapped } = toStitchDesignSystem(tokens);

  const client = await getStitchClient();
  const project = await client.project(projectId);
  await project.createDesignSystem(ds);

  const snapshot: DesignSystemSnapshot = {
    syncedAt: new Date().toISOString(),
    unmapped,
    raw: tokens,
  };
  await writeJsonAtomic(path.join(STITCH_DIR, "design-system.json"), snapshot);

  if (unmapped.length > 0) {
    console.warn(
      `stitch-sync-ds: ${unmapped.length} variables could not be mapped to the Stitch DesignSystem schema:`,
    );
    for (const u of unmapped) console.warn(`  - ${u}`);
    console.warn(`See docs/stitch-playbook.md for how to compensate verbally in prompts.`);
  }
  console.log(`stitch-sync-ds: synced ${Object.keys(tokens.colors).length} colors, ${Object.keys(tokens.typography).length} typography slots, ${Object.keys(tokens.spacing).length} spacing tokens.`);

  // Touch a marker so other scripts can compare freshness.
  void REPO_ROOT;
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
