/**
 * Pull canonical theme tokens from Figma and emit three artifacts:
 *   - dist/tokens/tokens.css        (CSS custom properties, root-scoped)
 *   - dist/tokens/tokens.json       (raw token tree, consumed by stitch-sync-design-system)
 *   - dist/tokens/tailwind.preset.js (Tailwind preset object, consumed by tailwind.config.ts)
 *
 * Also writes a TS module under src/tokens/ so React components can import them
 * type-safely without a CSS variable indirection (handy for runtime style props).
 *
 * Implementer note: when running inside Claude Code, prefer the figma MCP
 * (`mcp__figma__get_variable_defs`) over the REST call below. From the CLI we
 * fall back to the Figma REST API.
 */
import path from "node:path";
import { writeFile } from "node:fs/promises";
import { ensureDir, writeJsonAtomic } from "./_lib/fs.js";
import { DIST_TOKENS, REPO_ROOT } from "./_lib/paths.js";

interface TokenTree {
  colors: Record<string, string>;
  typography: Record<string, { family: string; weight?: number; size?: number; lineHeight?: number }>;
  spacing: Record<string, number>;
  radii: Record<string, number>;
  shadows: Record<string, string>;
}

async function fetchFromFigma(): Promise<TokenTree> {
  const fileKey = process.env.FIGMA_FILE_KEY;
  const token = process.env.FIGMA_API_TOKEN;
  if (!fileKey || !token) {
    console.warn("update-tokens: FIGMA_FILE_KEY or FIGMA_API_TOKEN missing; emitting starter token tree.");
    return STARTER_TOKENS;
  }
  // Real Figma fetch would call REST: /v1/files/<key>/variables/local
  // The shape depends on the file's variable collections. Keep this stub so the
  // pipeline runs end-to-end; the implementer fills in the parsing once the
  // canonical Figma file's variable layout is known.
  const res = await fetch(`https://api.figma.com/v1/files/${fileKey}/variables/local`, {
    headers: { "X-Figma-Token": token },
  });
  if (!res.ok) {
    console.warn(`update-tokens: Figma fetch failed (${res.status}); falling back to starter tokens.`);
    return STARTER_TOKENS;
  }
  // Implementer: parse `await res.json()` into TokenTree. For now, fall back.
  await res.json();
  return STARTER_TOKENS;
}

const STARTER_TOKENS: TokenTree = {
  colors: {
    "parchment-50": "#f8f1de",
    "parchment-100": "#f3e9d2",
    "parchment-200": "#e6d6ac",
    "ink-900": "#1c140d",
    "ink-700": "#2f221a",
    "ink-500": "#5b3a1e",
    "candle-500": "#d8b56b",
    "candle-700": "#a07a39",
    "rune-blue": "#4a6c8a",
    "rune-red": "#7a2828",
    "danger-500": "#a3201d",
    "success-500": "#3f6b3a",
  },
  typography: {
    display: { family: "Cinzel, serif", weight: 600, size: 28, lineHeight: 32 },
    "display-sm": { family: "Cinzel, serif", weight: 500, size: 20, lineHeight: 24 },
    body: { family: "EB Garamond, serif", weight: 400, size: 16, lineHeight: 24 },
    "body-sm": { family: "EB Garamond, serif", weight: 400, size: 14, lineHeight: 20 },
    mono: { family: "JetBrains Mono, monospace", weight: 400, size: 13, lineHeight: 20 },
  },
  spacing: { 0: 0, 1: 4, 2: 8, 3: 12, 4: 16, 5: 24, 6: 32, 7: 48, 8: 64 },
  radii: { sm: 2, md: 4, lg: 8, xl: 12 },
  shadows: {
    "candle-glow": "0 0 24px rgba(216, 181, 107, 0.35)",
    "ink-press": "inset 0 1px 0 rgba(28, 20, 13, 0.4)",
  },
};

function emitCss(t: TokenTree): string {
  const lines = [":root {"];
  for (const [n, v] of Object.entries(t.colors)) lines.push(`  --color-${n}: ${v};`);
  for (const [n, v] of Object.entries(t.spacing)) lines.push(`  --space-${n}: ${v}px;`);
  for (const [n, v] of Object.entries(t.radii)) lines.push(`  --radius-${n}: ${v}px;`);
  for (const [n, v] of Object.entries(t.shadows)) lines.push(`  --shadow-${n}: ${v};`);
  for (const [n, v] of Object.entries(t.typography)) {
    lines.push(`  --font-${n}: ${v.family};`);
    if (v.size) lines.push(`  --font-${n}-size: ${v.size}px;`);
    if (v.lineHeight) lines.push(`  --font-${n}-lh: ${v.lineHeight}px;`);
    if (v.weight) lines.push(`  --font-${n}-weight: ${v.weight};`);
  }
  lines.push("}");
  return lines.join("\n") + "\n";
}

function emitTailwindPreset(t: TokenTree): string {
  const colors = JSON.stringify(t.colors, null, 2);
  const spacing = JSON.stringify(
    Object.fromEntries(Object.entries(t.spacing).map(([k, v]) => [k, `${v}px`])),
    null,
    2,
  );
  const radii = JSON.stringify(
    Object.fromEntries(Object.entries(t.radii).map(([k, v]) => [k, `${v}px`])),
    null,
    2,
  );
  const shadows = JSON.stringify(t.shadows, null, 2);
  return `module.exports = {
  theme: {
    extend: {
      colors: ${colors},
      spacing: ${spacing},
      borderRadius: ${radii},
      boxShadow: ${shadows},
    },
  },
};
`;
}

function emitTs(t: TokenTree): string {
  return `// AUTO-GENERATED by scripts/update-tokens.ts. Do not edit.
export const tokens = ${JSON.stringify(t, null, 2)} as const;
export type Tokens = typeof tokens;
`;
}

async function main(): Promise<void> {
  const tokens = await fetchFromFigma();

  await ensureDir(DIST_TOKENS);
  await writeFile(path.join(DIST_TOKENS, "tokens.css"), emitCss(tokens), "utf8");
  await writeFile(path.join(DIST_TOKENS, "tailwind.preset.js"), emitTailwindPreset(tokens), "utf8");
  await writeJsonAtomic(path.join(DIST_TOKENS, "tokens.json"), tokens);

  const tsDir = path.join(REPO_ROOT, "src", "tokens");
  await ensureDir(tsDir);
  await writeFile(path.join(tsDir, "index.ts"), emitTs(tokens), "utf8");

  console.log(
    `update-tokens: emitted dist/tokens/{tokens.css,tokens.json,tailwind.preset.js} and src/tokens/index.ts (${Object.keys(tokens.colors).length} colors).`,
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
